### ISSUE TITLE
Impossible to Share Checklist

### ISSUE THREAD

**Issue by Sh1karno** [AndreySurzhan/ChecklistSLWebUi#38] opened 2019-10-04 13:59 UTC
**PC**
1. User should be login
2. Checklist should be created

**STR**
1. Click on imagebutton(Options)
2. Click on Share button

**ER**
The checklist sharing menu opens

**AR**
Nothing happens, the button does not work

**Comment by AndreySurzhan** [comment] 2019-10-04 17:50
Closed as not a bug. That functionality has not been implemented yet

**Closed by AndreySurzhan** 2019-10-04 17:50 UTC
Labels: bug, enhancement
